name: SAST SCAN USING SEMGREP
on: [push, pull_request]
jobs:
  CODE-SCANNING-USING-SEMGREP:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Scan Codebase
        run: semgrep --config "p/javascript" --error --sarif -o semgrep_vul.sarif

      - name: Upload SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3 # Updated to v3
        with:
          sarif_file: semgrep_vul.sarif
        if: always()
