name: Scan Pull Request Changes Using Bandit

on:
  pull_request:
    # Trigger the workflow if Python files are changed

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # Check out the pull request branch
          fetch-depth: 0  # Fetch all history for proper diffing

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install Bandit
      #   run: pip install bandit

      - name: Identify the Base Commit
        id: base-commit
        run: |
          BASE_COMMIT_SHA=$(git merge-base origin/${{ github.event.pull_request.base.ref }} HEAD)
          echo "Base commit: $BASE_COMMIT_SHA"
          echo "BASE_COMMIT_SHA=$BASE_COMMIT_SHA" >> $GITHUB_ENV
